# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Vex"
license = "MIT"
licenselink = "https://github.com/themefisher/vex-hugo/blob/master/LICENSE.md"
description = "Vex by Themefisher ported to Hugo"
homepage = "https://themefisher.com/products/vex-bootstrap4-product-landing-page-website-template/"
tags = ["onepage", "bootstrap", "product"]
features = ["onepage", "product"]
min_version = 0.15

[author]
  name = "Giacomo Mariani for Themefisher"
  homepage = "https://themefisher.com/"

# If porting an existing theme
[original]
  name = "Themefisher"
  homepage = "https://themefisher.com"
  repo = ""
