# theme.toml for the Vex Hugo theme

name = "Vex"
license = "MIT"
licenselink = "https://github.com/themefisher/vex-hugo/blob/master/LICENSE.md"
description = "Vex by Themefisher ported to Hugo"
homepage = "https://github.com/themefisher/vex-hugo"
tags = ["onepage", "bootstrap", "product"]
features = ["onepage", "product"]
min_version = 0.16

[author]
  name = "Giacomo Mariani for Themefisher"
  homepage = "https://themefisher.com/"

[original]
  name = "Vex"
  homepage = "https://themefisher.com/products/vex-bootstrap4-product-landing-page-website-template/"
  repo = ""
