############################# Default Configuration ############################
title = "Little Falls VA"
theme = "vex-hugo"
summarylength = 20
googleAnalytics = ""
disableLanguages = []
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe = true

############################## Language Configuration ###########################

defaultContentLanguage = "en"

[languages]
  default = "en"

  [languages.en]
    languageName = "En"
    languageCode = "en-us"
    contentDir = "content/english"
    weight = 1
    baseURL = "https://littlefallsva.com/"
    copyright = "©2023 Committe for Little Falls"

  [languages.es]
    languageName = "ES"
    languageCode = "es"
    contentDir = "content/spanish"
    weight = 2
    baseURL = "https://littlefallsva.com/es/"
    copyright = "©2023 Committe for Little Falls"

    [languages.es.permalinks]
      press = "/es/press/release/:year/:month/:day/:slug/"
      store = "/es/store/:title"
      about-us = "/es/:filename/"

[permalinks]
  press = "/press/release/:year/:month/:day/:slug/"
  store = "/store/:title/"
  about-us = "/:filename/"

############################### Plugins Configuration ############################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.js"

################################# Navigation Configuration ########################

# Homepage Section Menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Press & Media"
url = "press/"
weight = 2

[[menu.main]]
name = "Merch"
url = "store/"
weight = 3

[[menu.main]]
identifier = "petition"
name = "Petition"
url = "/petition/"
weight = 4

# Footer Menu
[[menu.footer]]
name = "Press & Media"
url = "press/"
weight = 1

[[menu.footer]]
name = "About Us"
url = "about-us/"
weight = 2

[[menu.footer]]
name = "Get Involved"
url = "get-involved/"
weight = 3

[[menu.footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 4

[[menu.footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 5

############################### Default Parameters ###########################

[params]
logo = "images/logo.png"
logo_width = "100px"
description = "This is meta description"
author = "Little Falls"
currency = "$"

# Preloader
[params.preloader]
enable = true
preloader = ""

# Snipcart
[params.snipcart]
enable = true
snipcart_api = "YTMxMWQyMDAtMzkzYS00YzQ5LWI4NWMtMDg2ZTZkYmZmYzZlNjM4MTY1MTA1Njc1MDgwMDIx"

[outputFormats]
[outputFormats.HTML]
  baseName = "index"

